### ISSUE TITLE
Lag in the data (1st of December)

### ISSUE THREAD

**Issue by lucasrodes** [crondonm/TrackingR#15]
Hi team!
I just realised that the data has not been updated since the 1st of December.

Has there been a change in the update frequency or a problem in the automation scripts? Let me know if you need help.

This is the file that we use: https://github.com/crondonm/TrackingR/blob/main/Estimates-Database/database_7.csv

Thanks!

**Comment by crondonm** [comment]
Hi @lucasrodes 

The repository is updated again.

Please let us know if you foresee needing daily updates or whether you think bimonthly updates will be fine.

Thanks a lot,

Carlos
