### ISSUE TITLE
Common mistake in the paper

### ISSUE THREAD

**Issue by CatChenal** [crondonm/TrackingR#2]
On page 4, the authors state that:
> "The recovered group consists of individuals who have either died or fully recovered."

This is incorrect as the S.I.R. model referenced is that of a _constant population S.I.R. model_ where the subpopulations S, I and R partition the overall population N, which is kept constant. Hence, R = {fully recovered (only)}.

**Comment by crondonm** [comment]
Where is the mistake exactly? We are assuming deaths and recoveries are both part of R, otherwise population will fall
