### ISSUE TITLE
US reproduction rate

### ISSUE THREAD

**Issue by RuijingZ** [crondonm/TrackingR#3]
Hello,

I found that the reproduction rate has not been updated for 10 days. May I ask if you will resume updating it?

https://github.com/crondonm/TrackingR/blob/main/Estimates-Database/database.csv

Thanks!

**Comment by crondonm** [comment]
Hi,

Thank you for letting me know. I had an issue with my security token and the repository wasn't updating properly. I fixed it know and should be working properly.

Please let me know if there are other issues.
