### ISSUE TITLE
Allow independent R calculation in countries reported by CSSE as Province/State

### ISSUE THREAD

**Issue by 3dgiordano** [crondonm/TrackingR#4]
Currently many independent countries or geographically distant from mainland are calculated inside the main country data.

This same problem Our World in Data was having with respect to cases and death data.
They recently began to make these data independent so that they can be consulted, and that they do not affect the statistics of the main country.
https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/jhu/__main__.py#L79

I made a program that allows you to see which countries are in this situation and can become independent of the calculation.
Otherwise you can align to the list that I shared from Our world in Data.
Our World in Data use TrackingR project, If you also separate these countries they will be able to show the R data of these countries.
 
Also in the example program I made them a routine to know which countries reported by CSSE are not really countries, I noticed that you have a filter but being static and as CSSE was incorporating other cases you would not be filtering them.
https://gist.github.com/3dgiordano/b2aea79f182e8c5aa59452366a90ddbc

```
* CSSE Sub-region to Region list
  American Samoa
  Anguilla
  Aruba
  Bermuda
  Bonaire, Sint Eustatius and Saba
  British Virgin Islands
  Cayman Islands
  Cook Islands
  Curacao
  Falkland Islands (Malvinas)
  Faroe Islands
  French Guiana
  French Polynesia
  Gibraltar
  Greenland
  Guadeloupe
  Guam
  Hong Kong
  Isle of Man
  Macau
  Martinique
  Mayotte
  Montserrat
  New Caledonia
  Northern Mariana Islands
  Reunion
  Saint Barthelemy
  Saint Helena, Ascension and Tristan da Cunha
  Saint Pierre and Miquelon
  Sint Maarten
  St Martin
  Turks and Caicos Islands
  Virgin Islands
  Wallis and Futuna

* CSSE Countries that are not countries
  Diamond Princess
  MS Zaandam
  Summer Olympics 2020
  ```

**Comment by crondonm** [comment]
This change can be done by the researchers if needed. For now, we will not update the code to include these countries/territories.
