### ISSUE TITLE
data has not been updated for a week

### ISSUE THREAD

**Issue by lucasrodes** [crondonm/TrackingR#5]
Hi! Thanks for your work, it helps us a lot at https://github.com/owid/covid-19-data.

Based on your guideline

> If you see a delay of three or more days, please let us know as this is probably due a to a technical issue with our GitHub repository. Instructions

I would like to bring to your attention that the last [database](https://github.com/crondonm/TrackingR/blob/main/Estimates-Database/database.csv) update took place on January 5th 2022 (>7 days). 

Hopefully, this is an easy fix :)

**Comment by udra69** [comment]
Thx for fixing so quickly!

**Comment by lucasrodes** [comment]
Seems to be solved
