### ISSUE TITLE
The data has not been updated since April 10

### ISSUE THREAD

**Issue by 3dgiordano** [crondonm/TrackingR#9]
Hi, thank you for keeping the project running.

I warn you that the data has not been updated since April 10.

According to the guide, if it takes three or more days to update, should be notified.

Regards
David

**Comment by crondonm** [comment]
Hi David,


We are aware of the issue and the next update should be up tomorrow (maybe today depending on how fast the estimation goes)

Thanks a lot for your email.

Carlos Rondón-Moreno, Ph.D
https://www.carlosrondonmoreno.com/

**Comment by 3dgiordano** [comment]
I see you guys have already fixed it.
I proceed to close the issue.
Thanks
